### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by kanchi240** [mentalisttraceur/robotframework-dependencylibrary#1]
C:\Users\admin>pip install robotframework-dependencylibrary
Collecting robotframework-dependencylibrary
  Using cached https://files.pythonhosted.org/packages/a1/e7/49027e1b0b6467aa42faf21a920bbc5e938be8fd76d9984240e41f8c3ebb/robotframework-dependencylibrary-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admin\appdata\local\temp\pip-build-27vbcu\robotframework-dependencylibrary\setup.py", line 11, in <module>
        with open(readme_path, encoding='utf-8') as readme_file:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-27vbcu\robotframework-dependencylibrary\
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Hi, is there something wrong?

**Comment by mentalisttraceur** [comment]
Hi, sorry, fixed now.

I uploaded a new version with the packaging fixed (1.0.0.post1) to PyPI. Try installing again and let me know.

**Comment by mentalisttraceur** [comment]
For anyone curious, the exact bug was that my `setup.py` (and thus `pip` install) was broken in Python 2 (worked fine with Python 3).

Specifically, `setup.py` was using a feature from Python 3 (the `encoding` argument to `open`).

I've since then fixed my `setup.py` to be more portable.

**Comment by kanchi240** [comment]
Thanks, @mentalisttraceur
