### ISSUE TITLE
Not work when depend more than 1 cases.

### ISSUE THREAD

**Issue by shadow1163** [mentalisttraceur/robotframework-dependencylibrary#2]
Hello, 
I have a, b, c 3 cases, I want case c depend with a and b. But I got error "DependencyLibrary.Depends On Test Success' expected 1 argument, got 2.'

**Comment by mentalisttraceur** [comment]
Does this work for you?

    *** Settings ***
    Library  DependencyLibrary

    *** Test cases ***
    a
        No operation

    b
        No operation

    c
        Depends on test    a
        Depends on test    b

**Comment by shadow1163** [comment]
it works, thank you
