### ISSUE TITLE
Suite not found

### ISSUE THREAD

**Issue by wlad** [mentalisttraceur/robotframework-dependencylibrary#4]
What am I missing or doing wrong?
![image](https://user-images.githubusercontent.com/64201310/114858301-948ad780-9de9-11eb-957a-0a45124b2827.png)

my folder structure
![image](https://user-images.githubusercontent.com/64201310/114858499-d3b92880-9de9-11eb-84e3-87d62c373acb.png)

Or do the test suites have to be in the same folder?

**Comment by mentalisttraceur** [comment]
Try passing just the name of the suite itself (`Data-Generation`) instead of the fully qualified name (`Robot.Data-Generation`) as the argument to `Depends on suite`.

**Comment by wlad** [comment]
thanks, that works
![image](https://user-images.githubusercontent.com/64201310/114938877-f0804b00-9e3f-11eb-9bef-c9f515946b5a.png)
